const elements = [
    { symbol: "H", name: "Hydrogen", atomicNumber: 1, category: "Nonmetal", uses: "Fuel, Rocket propellant", history: "Discovered by Henry Cavendish in 1766" },
    { symbol: "He", name: "Helium", atomicNumber: 2, category: "Noble gas", uses: "Balloons, Coolant", history: "Discovered by Pierre Janssen in 1868" },
    { symbol: "Li", name: "Lithium", atomicNumber: 3, category: "Alkali metal", uses: "Batteries, Medicine", history: "Discovered by Johann Arfvedson in 1817" },
    { symbol: "Be", name: "Beryllium", atomicNumber: 4, category: "Alkaline earth metal", uses: "Aerospace, X-ray windows", history: "Discovered by Louis Nicolas Vauquelin in 1798" },
    { symbol: "B", name: "Boron", atomicNumber: 5, category: "Metalloid", uses: "Glass, Detergents", history: "Discovered by Joseph Louis Gay-Lussac in 1808" },
    { symbol: "C", name: "Carbon", atomicNumber: 6, category: "Nonmetal", uses: "Fuel, Steel", history: "Known since ancient times" },
    { symbol: "N", name: "Nitrogen", atomicNumber: 7, category: "Nonmetal", uses: "Fertilizers, Explosives", history: "Discovered by Daniel Rutherford in 1772" },
    { symbol: "O", name: "Oxygen", atomicNumber: 8, category: "Nonmetal", uses: "Breathing, Steelmaking", history: "Discovered by Carl Wilhelm Scheele in 1774" },
    { symbol: "F", name: "Fluorine", atomicNumber: 9, category: "Halogen", uses: "Dental care, Teflon", history: "Discovered by Henri Moissan in 1886" },
    { symbol: "Ne", name: "Neon", atomicNumber: 10, category: "Noble gas", uses: "Lighting, Advertising signs", history: "Discovered by William Ramsay and Morris Travers in 1898" },
    { symbol: "Na", name: "Sodium", atomicNumber: 11, category: "Alkali metal", uses: "Salt, Batteries", history: "Discovered by Humphry Davy in 1807" },
    { symbol: "Mg", name: "Magnesium", atomicNumber: 12, category: "Alkaline earth metal", uses: "Aerospace, Pyrotechnics", history: "Discovered by Joseph Black in 1755" },
    { symbol: "Al", name: "Aluminium", atomicNumber: 13, category: "Post-transition metal", uses: "Packaging, Construction", history: "Discovered by Hans Christian Ørsted in 1825" },
    { symbol: "Si", name: "Silicon", atomicNumber: 14, category: "Metalloid", uses: "Electronics, Glass", history: "Discovered by Jöns Jacob Berzelius in 1824" },
    { symbol: "P", name: "Phosphorus", atomicNumber: 15, category: "Nonmetal", uses: "Fertilizers, Matches", history: "Discovered by Hennig Brand in 1669" },
    { symbol: "S", name: "Sulfur", atomicNumber: 16, category: "Nonmetal", uses: "Fertilizers, Gunpowder", history: "Known since ancient times" },
    { symbol: "Cl", name: "Chlorine", atomicNumber: 17, category: "Halogen", uses: "Disinfectants, PVC", history: "Discovered by Carl Wilhelm Scheele in 1774" },
    { symbol: "Ar", name: "Argon", atomicNumber: 18, category: "Noble gas", uses: "Lighting, Welding", history: "Discovered by Lord Rayleigh and William Ramsay in 1894" },
    { symbol: "K", name: "Potassium", atomicNumber: 19, category: "Alkali metal", uses: "Fertilizers, Salt substitutes", history: "Discovered by Humphry Davy in 1807" },
    { symbol: "Ca", name: "Calcium", atomicNumber: 20, category: "Alkaline earth metal", uses: "Cement, Bones", history: "Discovered by Humphry Davy in 1808" },
    { symbol: "Sc", name: "Scandium", atomicNumber: 21, category: "Transition metal", uses: "Aerospace, Lighting", history: "Discovered by Lars Fredrik Nilson in 1879" },
    { symbol: "Ti", name: "Titanium", atomicNumber: 22, category: "Transition metal", uses: "Aerospace, Medical implants", history: "Discovered by William Gregor in 1791" },
    { symbol: "V", name: "Vanadium", atomicNumber: 23, category: "Transition metal", uses: "Steel alloys, Catalysts", history: "Discovered by Andrés Manuel del Río in 1801" },
    { symbol: "Cr", name: "Chromium", atomicNumber: 24, category: "Transition metal", uses: "Stainless steel, Pigments", history: "Discovered by Louis Nicolas Vauquelin in 1797" },
    { symbol: "Mn", name: "Manganese", atomicNumber: 25, category: "Transition metal", uses: "Steel production, Batteries", history: "Discovered by Carl Wilhelm Scheele in 1774" },
    { symbol: "Fe", name: "Iron", atomicNumber: 26, category: "Transition metal", uses: "Steel, Magnets", history: "Known since ancient times" },
    { symbol: "Co", name: "Cobalt", atomicNumber: 27, category: "Transition metal", uses: "Magnets, Batteries", history: "Discovered by Georg Brandt in 1735" },
    { symbol: "Ni", name: "Nickel", atomicNumber: 28, category: "Transition metal", uses: "Stainless steel, Coins", history: "Discovered by Axel Fredrik Cronstedt in 1751" },
    { symbol: "Cu", name: "Copper", atomicNumber: 29, category: "Transition metal", uses: "Electrical wiring, Coins", history: "Known since ancient times" },
    { symbol: "Zn", name: "Zinc", atomicNumber: 30, category: "Transition metal", uses: "Galvanization, Alloys", history: "Known since ancient times" },
    { symbol: "Ga", name: "Gallium", atomicNumber: 31, category: "Post-transition metal", uses: "Electronics, Semiconductors", history: "Discovered by Paul-Émile Lecoq de Boisbaudran in 1875" },
    { symbol: "Ge", name: "Germanium", atomicNumber: 32, category: "Metalloid", uses: "Semiconductors, Optics", history: "Discovered by Clemens Winkler in 1886" },
    { symbol: "As", name: "Arsenic", atomicNumber: 33, category: "Metalloid", uses: "Pesticides, Alloys", history: "Known since ancient times" },
    { symbol: "Se", name: "Selenium", atomicNumber: 34, category: "Nonmetal", uses: "Glass, Electronics", history: "Discovered by Jöns Jacob Berzelius in 1817" },
    { symbol: "Br", name: "Bromine", atomicNumber: 35, category: "Halogen", uses: "Flame retardants, Photography", history: "Discovered by Antoine Jérôme Balard in 1826" },
    { symbol: "Kr", name: "Krypton", atomicNumber: 36, category: "Noble gas", uses: "Lighting, Photography", history: "Discovered by William Ramsay and Morris Travers in 1898" },
    { symbol: "Rb", name: "Rubidium", atomicNumber: 37, category: "Alkali metal", uses: "Research, Electronics", history: "Discovered by Robert Bunsen and Gustav Kirchhoff in 1861" },
    { symbol: "Sr", name: "Strontium", atomicNumber: 38, category: "Alkaline earth metal", uses: "Fireworks, Medical imaging", history: "Discovered by William Cruickshank in 1787" },
    { symbol: "Y", name: "Yttrium", atomicNumber: 39, category: "Transition metal", uses: "Lasers, Electronics", history: "Discovered by Johan Gadolin in 1794" },
    { symbol: "Zr", name: "Zirconium", atomicNumber: 40, category: "Transition metal", uses: "Nuclear reactors, Ceramics", history: "Discovered by Martin Heinrich Klaproth in 1789" },
    { symbol: "Nb", name: "Niobium", atomicNumber: 41, category: "Transition metal", uses: "Steel alloys, Superconductors", history: "Discovered by Charles Hatchett in 1801" },
    { symbol: "Mo", name: "Molybdenum", atomicNumber: 42, category: "Transition metal", uses: "Steel alloys, Catalysts", history: "Discovered by Carl Wilhelm Scheele in 1778" },
    { symbol: "Tc", name: "Technetium", atomicNumber: 43, category: "Transition metal", uses: "Medical imaging, Research", history: "Discovered by Carlo Perrier and Emilio Segrè in 1937" },
    { symbol: "Ru", name: "Ruthenium", atomicNumber: 44, category: "Transition metal", uses: "Electronics, Catalysts", history: "Discovered by Karl Ernst Claus in 1844" },
    { symbol: "Rh", name: "Rhodium", atomicNumber: 45, category: "Transition metal", uses: "Catalysts, Jewelry", history: "Discovered by William Hyde Wollaston in 1803" },
    { symbol: "Pd", name: "Palladium", atomicNumber: 46, category: "Transition metal", uses: "Catalysts, Jewelry", history: "Discovered by William Hyde Wollaston in 1803" },
    { symbol: "Ag", name: "Silver", atomicNumber: 47, category: "Transition metal", uses: "Jewelry, Electronics", history: "Known since ancient times" },
    { symbol: "Cd", name: "Cadmium", atomicNumber: 48, category: "Transition metal", uses: "Batteries, Pigments", history: "Discovered by Friedrich Stromeyer in 1817" },
    { symbol: "In", name: "Indium", atomicNumber: 49, category: "Post-transition metal", uses: "Electronics, Alloys", history: "Discovered by Ferdinand Reich and Hieronymous Theodor Richter in 1863" },
    { symbol: "Sn", name: "Tin", atomicNumber: 50, category: "Post-transition metal", uses: "Alloys, Coatings", history: "Known since ancient times" },
    { symbol: "Sb", name: "Antimony", atomicNumber: 51, category: "Metalloid", uses: "Flame retardants, Alloys", history: "Known since ancient times" },
    { symbol: "Te", name: "Tellurium", atomicNumber: 52, category: "Metalloid", uses: "Electronics, Alloys", history: "Discovered by Franz-Joseph Müller von Reichenstein in 1782" },
    { symbol: "I", name: "Iodine", atomicNumber: 53, category: "Halogen", uses: "Antiseptics, Photography", history: "Discovered by Bernard Courtois in 1811" },
    { symbol: "Xe", name: "Xenon", atomicNumber: 54, category: "Noble gas", uses: "Lighting, Anesthesia", history: "Discovered by William Ramsay and Morris Travers in 1898" },
    { symbol: "Cs", name: "Cesium", atomicNumber: 55, category: "Alkali metal", uses: "Atomic clocks, Electronics", history: "Discovered by Robert Bunsen and Gustav Kirchhoff in 1860" },
    { symbol: "Ba", name: "Barium", atomicNumber: 56, category: "Alkaline earth metal", uses: "Medical imaging, Fireworks", history: "Discovered by Carl Wilhelm Scheele in 1772" },
    { symbol: "La", name: "Lanthanum", atomicNumber: 57, category: "Lanthanide", uses: "Optics, Catalysts", history: "Discovered by Carl Gustaf Mosander in 1839" },
    { symbol: "Ce", name: "Cerium", atomicNumber: 58, category: "Lanthanide", uses: "Glass, Catalysts", history: "Discovered by Martin Heinrich Klaproth in 1803" },
    { symbol: "Pr", name: "Praseodymium", atomicNumber: 59, category: "Lanthanide", uses: "Magnets, Glass", history: "Discovered by Carl Auer von Welsbach in 1885" },
    { symbol: "Nd", name: "Neodymium", atomicNumber: 60, category: "Lanthanide", uses: "Magnets, Glass", history: "Discovered by Carl Auer von Welsbach in 1885" },
    { symbol: "Pm", name: "Promethium", atomicNumber: 61, category: "Lanthanide", uses: "Research, Nuclear batteries", history: "Discovered by Jacob A. Marinsky, Lawrence E. Glendenin, and Charles D. Coryell in 1945" },
    { symbol: "Sm", name: "Samarium", atomicNumber: 62, category: "Lanthanide", uses: "Magnets, Cancer treatment", history: "Discovered by Paul-Émile Lecoq de Boisbaudran in 1879" },
    { symbol: "Eu", name: "Europium", atomicNumber: 63, category: "Lanthanide", uses: "Phosphorescent materials, Nuclear reactors", history: "Discovered by Eugène-Anatole Demarçay in 1896" },
    { symbol: "Gd", name: "Gadolinium", atomicNumber: 64, category: "Lanthanide", uses: "Medical imaging, Neutron capture", history: "Discovered by Jean Charles Galissard de Marignac in 1880" },
    { symbol: "Tb", name: "Terbium", atomicNumber: 65, category: "Lanthanide", uses: "Phosphorescent materials, Electronics", history: "Discovered by Carl Gustaf Mosander in 1843" },
    { symbol: "Dy", name: "Dysprosium", atomicNumber: 66, category: "Lanthanide", uses: "Magnets, Nuclear reactors", history: "Discovered by Paul-Émile Lecoq de Boisbaudran in 1886" },
    { symbol: "Ho", name: "Holmium", atomicNumber: 67, category: "Lanthanide", uses: "Magnets, Lasers", history: "Discovered by Marc Delafontaine and Jacques-Louis Soret in 1878" },
    { symbol: "Er", name: "Erbium", atomicNumber: 68, category: "Lanthanide", uses: "Lasers, Glass", history: "Discovered by Carl Gustaf Mosander in 1843" },
    { symbol: "Tm", name: "Thulium", atomicNumber: 69, category: "Lanthanide", uses: "Lasers, Medical imaging", history: "Discovered by Per Teodor Cleve in 1879" },
    { symbol: "Yb", name: "Ytterbium", atomicNumber: 70, category: "Lanthanide", uses: "Lasers, Nuclear reactors", history: "Discovered by Jean Charles Galissard de Marignac in 1878" },
    { symbol: "Lu", name: "Lutetium", atomicNumber: 71, category: "Lanthanide", uses: "Catalysts, Medical imaging", history: "Discovered by Georges Urbain in 1907" },
    { symbol: "Hf", name: "Hafnium", atomicNumber: 72, category: "Transition metal", uses: "Nuclear reactors, Alloys", history: "Discovered by Dirk Coster and George de Hevesy in 1923" },
    { symbol: "Ta", name: "Tantalum", atomicNumber: 73, category: "Transition metal", uses: "Electronics, Alloys", history: "Discovered by Anders Gustaf Ekeberg in 1802" },
    { symbol: "W", name: "Tungsten", atomicNumber: 74, category: "Transition metal", uses: "Light bulbs, Cutting tools", history: "Discovered by Carl Wilhelm Scheele in 1781" },
    { symbol: "Re", name: "Rhenium", atomicNumber: 75, category: "Transition metal", uses: "Jet engines, Catalysts", history: "Discovered by Masataka Ogawa in 1908" },
    { symbol: "Os", name: "Osmium", atomicNumber: 76, category: "Transition metal", uses: "Alloys, Electrical contacts", history: "Discovered by Smithson Tennant in 1803" },
    { symbol: "Ir", name: "Iridium", atomicNumber: 77, category: "Transition metal", uses: "Alloys, Electrical contacts", history: "Discovered by Smithson Tennant in 1803" },
    { symbol: "Pt", name: "Platinum", atomicNumber: 78, category: "Transition metal", uses: "Jewelry, Catalysts", history: "Known since ancient times" },
    { symbol: "Au", name: "Gold", atomicNumber: 79, category: "Transition metal", uses: "Jewelry, Electronics", history: "Known since ancient times" },
    { symbol: "Hg", name: "Mercury", atomicNumber: 80, category: "Transition metal", uses: "Thermometers, Electrical switches", history: "Known since ancient times" },
    { symbol: "Tl", name: "Thallium", atomicNumber: 81, category: "Post-transition metal", uses: "Electronics, Medicine", history: "Discovered by William Crookes in 1861" },
    { symbol: "Pb", name: "Lead", atomicNumber: 82, category: "Post-transition metal", uses: "Batteries, Radiation shielding", history: "Known since ancient times" },
    { symbol: "Bi", name: "Bismuth", atomicNumber: 83, category: "Post-transition metal", uses: "Medicine, Pigments", history: "Known since ancient times" },
    { symbol: "Po", name: "Polonium", atomicNumber: 84, category: "Metalloid", uses: "Research, Nuclear batteries", history: "Discovered by Marie Curie in 1898" },
    { symbol: "At", name: "Astatine", atomicNumber: 85, category: "Metalloid", uses: "Research, Medicine", history: "Discovered by Dale R. Corson, Kenneth Ross MacKenzie, and Emilio Segrè in 1940" },
    { symbol: "Rn", name: "Radon", atomicNumber: 86, category: "Noble gas", uses: "Medical treatment, Research", history: "Discovered by Friedrich Ernst Dorn in 1900" },
    { symbol: "Fr", name: "Francium", atomicNumber: 87, category: "Alkali metal", uses: "Research", history: "Discovered by Marguerite Perey in 1939" },
    { symbol: "Ra", name: "Radium", atomicNumber: 88, category: "Alkaline earth metal", uses: "Cancer treatment, Research", history: "Discovered by Pierre and Marie Curie in 1898" },
    { symbol: "Ac", name: "Actinium", atomicNumber: 89, category: "Actinide", uses: "Research, Radiation therapy", history: "Discovered by Friedrich Oskar Giesel in 1902" },
    { symbol: "Th", name: "Thorium", atomicNumber: 90, category: "Actinide", uses: "Nuclear reactors, Alloys", history: "Discovered by Jöns Jacob Berzelius in 1828" },
    { symbol: "Pa", name: "Protactinium", atomicNumber: 91, category: "Actinide", uses: "Research", history: "Discovered by Kasimir Fajans and Oswald Helmuth Göhring in 1913" },
    { symbol: "U", name: "Uranium", atomicNumber: 92, category: "Actinide", uses: "Nuclear fuel, Weapons", history: "Discovered by Martin Heinrich Klaproth in 1789" },
    { symbol: "Np", name: "Neptunium", atomicNumber: 93, category: "Actinide", uses: "Research", history: "Discovered by Edwin McMillan and Philip H. Abelson in 1940" },
    { symbol: "Pu", name: "Plutonium", atomicNumber: 94, category: "Actinide", uses: "Nuclear fuel, Weapons", history: "Discovered by Glenn T. Seaborg, Arthur Wahl, and Joseph W. Kennedy in 1940" },
    { symbol: "Am", name: "Americium", atomicNumber: 95, category: "Actinide", uses: "Smoke detectors, Research", history: "Discovered by Glenn T. Seaborg, Ralph A. James, and Albert Ghiorso in 1944" },
    { symbol: "Cm", name: "Curium", atomicNumber: 96, category: "Actinide", uses: "Research", history: "Discovered by Glenn T. Seaborg, Ralph A. James, and Albert Ghiorso in 1944" },
    { symbol: "Bk", name: "Berkelium", atomicNumber: 97, category: "Actinide", uses: "Research", history: "Discovered by Glenn T. Seaborg, Albert Ghiorso, Stanley G. Thompson, and Kenneth Street Jr. in 1949" },
    { symbol: "Cf", name: "Californium", atomicNumber: 98, category: "Actinide", uses: "Research, Nuclear reactors", history: "Discovered by Glenn T. Seaborg, Stanley G. Thompson, Albert Ghiorso, and Kenneth Street Jr. in 1950" },
    { symbol: "Es", name: "Einsteinium", atomicNumber: 99, category: "Actinide", uses: "Research", history: "Discovered by Albert Ghiorso and coworkers in 1952" },
    { symbol: "Fm", name: "Fermium", atomicNumber: 100, category: "Actinide", uses: "Research", history: "Discovered by Albert Ghiorso and coworkers in 1952" },
    { symbol: "Md", name: "Mendelevium", atomicNumber: 101, category: "Actinide", uses: "Research", history: "Discovered by Albert Ghiorso, Bernard Harvey, Gregory R. Choppin, Stanley G. Thompson, and Glenn T. Seaborg in 1955" },
    { symbol: "No", name: "Nobelium", atomicNumber: 102, category: "Actinide", uses: "Research", history: "Discovered by Albert Ghiorso, Torbjørn Sikkeland, John R. Walton, and Glenn T. Seaborg in 1958" },
    { symbol: "Lr", name: "Lawrencium", atomicNumber: 103, category: "Actinide", uses: "Research", history: "Discovered by Albert Ghiorso, Torbjørn Sikkeland, Almon Larsh, and Robert M. Latimer in 1961" },
    { symbol: "Rf", name: "Rutherfordium", atomicNumber: 104, category: "Transition metal", uses: "Research", history: "Discovered by Georgy Flerov and coworkers in 1964" },
    { symbol: "Db", name: "Dubnium", atomicNumber: 105, category: "Transition metal", uses: "Research", history: "Discovered by Georgy Flerov and coworkers in 1967" },
    { symbol: "Sg", name: "Seaborgium", atomicNumber: 106, category: "Transition metal", uses: "Research", history: "Discovered by Albert Ghiorso and coworkers in 1974" },
    { symbol: "Bh", name: "Bohrium", atomicNumber: 107, category: "Transition metal", uses: "Research", history: "Discovered by Peter Armbruster and Gottfried Münzenberg in 1981" },
    { symbol: "Hs", name: "Hassium", atomicNumber: 108, category: "Transition metal", uses: "Research", history: "Discovered by Peter Armbruster and Gottfried Münzenberg in 1984" },
    { symbol: "Mt", name: "Meitnerium", atomicNumber: 109, category: "Transition metal", uses: "Research", history: "Discovered by Peter Armbruster and Gottfried Münzenberg in 1982" },
    { symbol: "Ds", name: "Darmstadtium", atomicNumber: 110, category: "Transition metal", uses: "Research", history: "Discovered by Sigurd Hofmann and coworkers in 1994" },
    { symbol: "Rg", name: "Roentgenium", atomicNumber: 111, category: "Transition metal", uses: "Research", history: "Discovered by Sigurd Hofmann and coworkers in 1994" },
    { symbol: "Cn", name: "Copernicium", atomicNumber: 112, category: "Transition metal", uses: "Research", history: "Discovered by Sigurd Hofmann and coworkers in 1996" },
    { symbol: "Nh", name: "Nihonium", atomicNumber: 113, category: "Post-transition metal", uses: "Research", history: "Discovered by Kosuke Morita and coworkers in 2003" },
    { symbol: "Fl", name: "Flerovium", atomicNumber: 114, category: "Post-transition metal", uses: "Research", history: "Discovered by Yuri Oganessian and coworkers in 1998" },
    { symbol: "Mc", name: "Moscovium", atomicNumber: 115, category: "Post-transition metal", uses: "Research", history: "Discovered by Yuri Oganessian and coworkers in 2003" },
    { symbol: "Lv", name: "Livermorium", atomicNumber: 116, category: "Post-transition metal", uses: "Research", history: "Discovered by Yuri Oganessian and coworkers in 2000" },
    { symbol: "Ts", name: "Tennessine", atomicNumber: 117, category: "Halogen", uses: "Research", history: "Discovered by Yuri Oganessian and coworkers in 2010" },
    { symbol: "Og", name: "Oganesson", atomicNumber: 118, category: "Noble gas", uses: "Research", history: "Discovered by Yuri Oganessian and coworkers in 2002" }
];