$(document).ready(function(){
    $(".start").click(function(){
        $(".front").hide();
        $(".maker").show();
        $(".color1").click(function(){
            $(".emoji").css('backgroundColor',"#ffd21f");
        });
        $(".nxt1").click(function(){
            $(".tone").hide();
            $(".eyes").show();
        });
        $(".bck2").click(function(){
            $(".tone").show();
            $(".eyes").hide();
        });
        $(".nxt2").click(function(){
            $(".eyes").hide();
            $(".brows").show();
        });
        $(".bck3").click(function(){
            $(".eyes").show();
            $(".brows").hide();
        });
        $(".nxt3").click(function(){
            $(".brows").hide();
            $(".mouths").show();
        });
        $(".bck4").click(function(){
            $(".brows").show();
            $(".mouths").hide();
        });
        $(".nxt4").click(function(){
            $(".mouths").hide();
            $(".miscs").show();
        });
        $(".bck5").click(function(){
            $(".mouths").show();
            $(".miscs").hide();
        });
        $(".nxt5").click(function(){
            $(".miscs").hide();
            $(".last").show();
            $(".emoji").css({
                top: '80px',
                animation: 'ready 1s infinite'
            });
        });
        $(".color2").click(function(){
            $(".emoji").css('backgroundColor',"#66b3ff    ");
        });
        $(".color3").click(function(){
            $(".emoji").css('backgroundColor',"tomato");
        });
        $(".color4").click(function(){
            $(".emoji").css('backgroundColor',"#663399");
        });
        $(".color5").click(function(){
            $(".emoji").css('backgroundColor',"#6cff47");
        });
        
        $(".eye1").click(function(){
            $(".eye").css('background',"url(https://i.imgur.com/38xgEQx.png)");
        });
        $(".eye2").click(function(){
            $(".eye").css('background',"url(https://i.imgur.com/4qyeHYa.png)");
        });
        $(".eye3").click(function(){
            $(".eye").css('background',"url(https://i.imgur.com/L5L4DDL.png)");
        });
        $(".eye4").click(function(){
            $(".eye").css('background',"url(https://i.imgur.com/yiRGWEA.png)");
        });
        $(".eye5").click(function(){
            $(".eye").css('background',"url(https://i.imgur.com/JGyB1KV.png)");
        });
        $(".eye6").click(function(){
            $(".eye").css('background',"url(https://i.imgur.com/xbxtXCR.png)");
        });
        $(".eye7").click(function(){
            $(".eye").css('background',"url(https://i.imgur.com/tzB1pv0.png)");
        });
        $(".eye8").click(function(){
            $(".eye").css('background',"url(https://i.imgur.com/rKwvyJD.png)");
        });
        $(".brow1").click(function(){
            $(".brow").css('background',"url(https://i.imgur.com/ia2ixe6.png)");
        });
        $(".brow2").click(function(){
            $(".brow").css('background',"url(https://i.imgur.com/Q805PQl.png)");
        });
        $(".brow3").click(function(){
            $(".brow").css('background',"url(https://i.imgur.com/7PFr6aS.png)");
        });
        $(".brow4").click(function(){
            $(".brow").css('background',"url(https://i.imgur.com/HByut6R.png)");
        });
        $(".brow5").click(function(){
            $(".brow").css('background',"transparent");
        });
        $(".mouth1").click(function(){
            $(".mouth").css('background',"url(https://i.imgur.com/qNI3rU2.png)");
        });
        $(".mouth2").click(function(){
            $(".mouth").css('background',"url(https://i.imgur.com/UVgQlSF.png)");
        });
        $(".mouth3").click(function(){
            $(".mouth").css('background',"url(https://i.imgur.com/7lWZIhm.png)");
        });
        $(".mouth4").click(function(){
            $(".mouth").css('background',"url(https://i.imgur.com/JMClEHb.png)");
        });
        $(".mouth5").click(function(){
            $(".mouth").css('background',"url(https://i.imgur.com/t47iR6d.png)");
        });
        $(".mouth6").click(function(){
            $(".mouth").css('background',"url(https://i.imgur.com/v7RH7VT.png)");
        });
        $(".mouth7").click(function(){
            $(".mouth").css('background',"url(https://i.imgur.com/ijp1twU.png)");
        });
        $(".mouth8").click(function(){
            $(".mouth").css('background',"url(https://i.imgur.com/tzQ01ks.png)");
        });
        $(".mouth9").click(function(){
            $(".mouth").css('background',"url(https://i.imgur.com/7xzhU2f.png)");
        });
        $(".misc1").click(function(){
            $(".misc").css({
                background:'url(https://i.imgur.com/petB4jd.png)',
                bottom:'50px',
                left:'10px'
            });
        });
        $(".misc2").click(function(){
            $(".misc").css({
                background:'url(https://i.imgur.com/mp9OgEI.png)',
                bottom:'135px',
                left:'80px'
            });
        });
        $(".misc3").click(function(){
            $(".misc").css({
                background:'url(https://i.imgur.com/TWAvrLc.png)',
                bottom:'15px',
                left:'13px'
            });
        });
        $(".misc4").click(function(){
            $(".misc").css({
                background:'url(https://i.imgur.com/IJfAMdf.png)',
                bottom:'145px',
                left:'10px'
            });
        });
        $(".misc5").click(function(){
            $(".misc").css('background',"transparent");
        });
    });
});